baseURL = 'https://reports.muthu.co/'
languageCode = 'en-us'
title = 'Annual Report Insights'
theme = 'typo'

# Google analytics code
googleAnalytics = "G-T7PH4WNH24"

[taxonomies]
tag = 'tags'

[params]
# Meta description
description = "Discover key takeaways and essential highlights from the latest annual reports of top companies and organizations. Our concise summaries help you stay informed about financial performance, strategic goals, and future trends, saving you time and offering valuable insights in an easy-to-read format."
showFooter = true
footerContent = "Made with â™¥ in India"

# Appearance settings
theme = 'light'
colorPalette = 'catpuccin'
hideHeader = true

# Intro on main page, content is markdown
# homeIntroTitle = 'Hello!'
# homeIntroContent = ""

# Collection to display on home
homeCollectionTitle = 'Latest Annual Reports'
homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = false
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

# Social icons
# [[params.social]]
# name = "linkedin"
# url = "https://www.linkedin.com/in/krimuthu/"

# [[params.social]]
# name = "github"
# url = "https://github.com/muthuspark"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

# [[params.menu]]
# name = "posts"
# url = "/posts"

[[params.menu]]
name = "about"
url = "/about"

# Giscus comments
[params.giscus]
enable = false
repo = "muthuspark/annual-reports"
repoid = "R_kgDON50MsQ"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"